from core.qt_core import *
from images import IMAGES
from widgets import RarityButton, WeaponButton

class Weapons(QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        
        _layout = QVBoxLayout(self)
        _layout.setContentsMargins(0, 0, 0, 0)
        
        self.scroll_area = QScrollArea(self)
        self.scroll_area.setObjectName("ScrollArea")
        self.scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scroll_area.setFrameShape(QFrame.Shape.NoFrame)
        self.scroll_area.setWidgetResizable(True)
        self.content_area = QWidget(self)
        self.content_area.setObjectName("Content")
        self.scroll_area.setWidget(self.content_area)
        _layout.addWidget(self.scroll_area)
        
        self._layout = QVBoxLayout(self.content_area)
        self._layout.setContentsMargins(0, 0, 9, 0)
        self._layout.setAlignment(Qt.AlignmentFlag.AlignTop)
        self.line_width = 2
        
        self.weapons_label = QLabel(self.content_area, text="Weapons")
        self.weapons_label.setContentsMargins(0, 0, 0, 15)
        self.weapons_label.setObjectName("ItemsHeaderName")
        
        self.weapons_container = QWidget(self.content_area)
        self.weapons_container_layout = QGridLayout(self.weapons_container)
        self.weapons_container_layout.setAlignment(Qt.AlignmentFlag.AlignLeft)
        self.weapons_container_layout.setContentsMargins(10, 0, 0, 0)
        
        self.common_button = RarityButton(self.weapons_container, "Common")
        self.uncommon_button = RarityButton(self.weapons_container, "Uncommon")
        self.rare_button = RarityButton(self.weapons_container, "Rare")
        self.epic_button = RarityButton(self.weapons_container, "Epic")
        self.legendary_button = RarityButton(self.weapons_container, "Legendary")
        self.rare_button.select()
        
        self.pistol_button = WeaponButton(self, QPixmap(IMAGES["pistol_color"]), weapon_id=0)
        self.dualies_button = WeaponButton(self, QPixmap(IMAGES["dualies_color"]), weapon_id=1)
        self.magnum_button = WeaponButton(self, QPixmap(IMAGES["magnum_color"]), weapon_id=2)
        self.deagle_button = WeaponButton(self, QPixmap(IMAGES["deagle_color"]), weapon_id=3)
        self.silenced_pistol_button = WeaponButton(self, QPixmap(IMAGES["silenced_pistol_color"]), weapon_id=4)
        self.shotgun_button = WeaponButton(self, QPixmap(IMAGES["shotgun_color"]), weapon_id=5)
        self.jag7_button = WeaponButton(self, QPixmap(IMAGES["jag7_color"]), weapon_id=6)
        self.smg_button = WeaponButton(self, QPixmap(IMAGES["smg_color"]), weapon_id=7)
        self.tommy_gun_button = WeaponButton(self, QPixmap(IMAGES["tommy_gun_color"]), weapon_id=8)
        self.ak_button = WeaponButton(self, QPixmap(IMAGES["ak_color"]), weapon_id=9)
        self.m16_button = WeaponButton(self, QPixmap(IMAGES["m16_color"]), weapon_id=10)
        self.dart_gun_button = WeaponButton(self, QPixmap(IMAGES["dart_gun_color"]), weapon_id=11)
        self.dartfly_gun_button = WeaponButton(self, QPixmap(IMAGES["dartfly_gun_color"]), weapon_id=12)
        self.hunting_rifle_button = WeaponButton(self, QPixmap(IMAGES["hunting_rifle_color"]), weapon_id=13)
        self.sniper_button = WeaponButton(self, QPixmap(IMAGES["sniper_color"]), weapon_id=14)
        self.superite_laser_button = WeaponButton(self, QPixmap(IMAGES["superite_laser_color"]), weapon_id=15)
        self.minigun_button = WeaponButton(self, QPixmap(IMAGES["minigun_color"]), weapon_id=16)
        self.bow_button = WeaponButton(self, QPixmap(IMAGES["bow_color"]), weapon_id=17)
        self.sparrow_launcher_button = WeaponButton(self, QPixmap(IMAGES["sparrow_launcher_color"]), weapon_id=18)
        self.bcg_button = WeaponButton(self, QPixmap(IMAGES["bcg_color"]), weapon_id=19)
        
        self.weapons_container_layout.addWidget(self.common_button, 0, 0)
        self.weapons_container_layout.addWidget(self.uncommon_button, 0, 1)
        self.weapons_container_layout.addWidget(self.rare_button, 0, 2)
        self.weapons_container_layout.addWidget(self.epic_button, 0, 3)
        self.weapons_container_layout.addWidget(self.legendary_button, 0, 4)
        self.weapons_container_layout.addWidget(self.pistol_button, 1, 0)
        self.weapons_container_layout.addWidget(self.dualies_button, 1, 1)
        self.weapons_container_layout.addWidget(self.magnum_button, 1, 2)
        self.weapons_container_layout.addWidget(self.deagle_button, 1, 3)
        self.weapons_container_layout.addWidget(self.silenced_pistol_button, 1, 4)
        self.weapons_container_layout.addWidget(self.shotgun_button, 2, 0)
        self.weapons_container_layout.addWidget(self.jag7_button, 2, 1)
        self.weapons_container_layout.addWidget(self.smg_button, 2, 2)
        self.weapons_container_layout.addWidget(self.tommy_gun_button, 2, 3)
        self.weapons_container_layout.addWidget(self.ak_button, 2, 4)
        self.weapons_container_layout.addWidget(self.m16_button, 3, 0)
        self.weapons_container_layout.addWidget(self.dart_gun_button, 3, 1)
        self.weapons_container_layout.addWidget(self.dartfly_gun_button, 3, 2)
        self.weapons_container_layout.addWidget(self.hunting_rifle_button, 3, 3)
        self.weapons_container_layout.addWidget(self.sniper_button, 3, 4)
        self.weapons_container_layout.addWidget(self.superite_laser_button, 4, 0)
        self.weapons_container_layout.addWidget(self.minigun_button, 4, 1)
        self.weapons_container_layout.addWidget(self.bow_button, 4, 2)
        self.weapons_container_layout.addWidget(self.sparrow_launcher_button, 4, 3)
        self.weapons_container_layout.addWidget(self.bcg_button, 4, 4)
        
        self._layout.addWidget(self.weapons_label)
        self._layout.addWidget(self.weapons_container)